{% set name = "xbbg" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alpha-xone/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fa74386bb57c592d7987b4fb92cbcb80559a3193f367f91cc560e3c8dd25aea7


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pypandoc
    - setuptools
  run:
    - python >={{ python_min }}
    - blpapi
    - numpy >=1.15.0
    - pandas >=1.0.0,<=1.5.3
    - pyarrow >=1.0.1
    - pytz >=2020.4
    - ruamel.yaml >=0.15.0
    - pytest

test:
  imports:
    - xbbg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alpha-xone/xbbg
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Intuitive Bloomberg data API
  doc_url: https://xbbg.readthedocs.io
  dev_url: https://github.com/alpha-xone/xbbg

extra:
  recipe-maintainers:
    - marcobonifacio
