{% set name = "xbbg" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alpha-xone/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cb318cadb109afe9d797930ceeac5de1a3639111d79e57369e62d44b98ee553a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pypandoc
  run:
    - python >=3.6
    - blpapi
    - numpy >=1.15.0
    - pandas >=1.0.0
    - pyarrow >=1.0.1
    - pytz >=2020.4
    - ruamel.yaml >=0.15.0
    - pytest

test:
  imports:
    - xbbg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alpha-xone/xbbg
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Intuitive Bloomberg data API
  doc_url: https://xbbg.readthedocs.io
  dev_url: https://github.com/alpha-xone/xbbg

extra:
  recipe-maintainers:
    - marcobonifacio
