{% set name = "xbbg" %}
{% set version = "0.11.0b5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alpha-xone/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3ce88544588649590e53a8e4766ca566b6950729fba9c724e87a318d1f2140ff

build:
  noarch: python
  number: 0
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools >=77
    - setuptools_scm >=8
    - wheel
  run:
    - python >={{ python_min }}
    - blpapi
    - narwhals >=2.14.0
    - numpy >=2.2.6
    - pandas >=2.0
    - pyarrow >=22.0.0

test:
  imports:
    - xbbg
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/alpha-xone/xbbg
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Intuitive Bloomberg data API
  doc_url: https://xbbg.readthedocs.io
  dev_url: https://github.com/alpha-xone/xbbg

extra:
  recipe-maintainers:
    - kj55-dev
    - makoponi
