{% set name = "xbbg" %}
{% set version = "1.0.0b7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alpha-xone/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 65e8978f723eb1e8d2b82a871e437e8b50ba40891d2882cbeb5157227f111ca2

build:
  number: 0
  skip: true  # [osx and x86_64]
  script:
    - export BLPAPI_INCLUDE_DIR=$PREFIX/include           # [unix]
    - export BLPAPI_LIB_DIR=$PREFIX/lib                   # [unix]
    - set BLPAPI_INCLUDE_DIR=%LIBRARY_PREFIX%\include     # [win]
    - set BLPAPI_LIB_DIR=%LIBRARY_PREFIX%\lib             # [win]
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}     # [win]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cargo-bundle-licenses
    - libclang-cpp
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools >=82
    - setuptools-rust >=1.12
    - setuptools-scm >=9
    - wheel >=0.46
    - libblpapi-devel
  run:
    - python
    - narwhals >=1.30
    - pyarrow >=22.0.0

test:
  imports:
    - xbbg
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/alpha-xone/xbbg
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Intuitive Bloomberg data API
  doc_url: https://xbbg.readthedocs.io
  dev_url: https://github.com/alpha-xone/xbbg

extra:
  recipe-maintainers:
    - kj55-dev
    - makoponi
