{% set name = "xbbg" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alpha-xone/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2171dbc9016cb4cda7c43b4f50d103c905109079676d6602f4359a8bef33e35b

build:
  noarch: python
  number: 0
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools >=77
    - setuptools_scm >=8
    - wheel
  run:
    - python >={{ python_min }}
    - blpapi
    - numpy >=2.2.6
    - pandas >=2.0,<=2.3.0
    - pandas_market_calendars >=5.1.3
    - pyarrow >=22.0.0
    - python-stdnum >=2.1
    - pytz >=2025.2
    - ruamel.yaml >=0.18.16
    - pytest >=8.4.2

test:
  imports:
    - xbbg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alpha-xone/xbbg
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Intuitive Bloomberg data API
  doc_url: https://xbbg.readthedocs.io
  dev_url: https://github.com/alpha-xone/xbbg

extra:
  recipe-maintainers:
    - kj55-dev
    - makoponi
